const cheerio = require('cheerio');
const fs = require('fs/promises');
const path = require('path');

async function main() {
  const items = {
    ...{
      // 六月更新
      LaserRifle: '激光步槍 (常見)',
      LaserRifle_2: '激光步槍 (少見)',
      LaserRifle_3: '激光步槍 (稀有)',
      LaserRifle_4: '激光步槍 (史詩)',
      LaserRifle_5: '激光步槍 (傳奇)',
      LaserRifle_NPC: '激光步槍 (NPC)',
      Blueprint_LaserRifle_2: '激光步槍設計圖1',
      Blueprint_LaserRifle_3: '激光步槍設計圖2',
      Blueprint_LaserRifle_4: '激光步槍設計圖3',
      Blueprint_LaserRifle_5: '激光步槍設計圖4',
      LaserBullet: '能量盒',
      GuidedMissileLauncher: '追蹤導彈發射器 (常見)',
      GuidedMissileLauncher_2: '追蹤導彈發射器 (少見)',
      GuidedMissileLauncher_3: '追蹤導彈發射器 (稀有)',
      GuidedMissileLauncher_4: '追蹤導彈發射器 (史詩)',
      GuidedMissileLauncher_5: '追蹤導彈發射器 (傳奇)',
      Blueprint_GuidedMissileLauncher_2: '追蹤導彈發射器設計圖2',
      Blueprint_GuidedMissileLauncher_3: '追蹤導彈發射器設計圖3',
      Blueprint_GuidedMissileLauncher_4: '追蹤導彈發射器設計圖4',
      Blueprint_GuidedMissileLauncher_5: '追蹤導彈發射器設計圖5',
      MultiGuidedMissileLauncher: '多聯裝追蹤導彈發射器 (常見)',
      MultiGuidedMissileLauncher_2: '多聯裝追蹤導彈發射器 (少見)',
      MultiGuidedMissileLauncher_3: '多聯裝追蹤導彈發射器 (稀有)',
      MultiGuidedMissileLauncher_4: '多聯裝追蹤導彈發射器 (史詩)',
      MultiGuidedMissileLauncher_5: '多聯裝追蹤導彈發射器 (傳奇)',
      Blueprint_MultiGuidedMissileLauncher_2: '多聯裝追蹤導彈發射器設計圖1',
      Blueprint_MultiGuidedMissileLauncher_3: '多聯裝追蹤導彈發射器設計圖2',
      Blueprint_MultiGuidedMissileLauncher_4: '多聯裝追蹤導彈發射器設計圖3',
      Blueprint_MultiGuidedMissileLauncher_5: '多聯裝追蹤導彈發射器設計圖4',
      MissileBullet: '導彈',
      GatlingGun: '加特林機槍 (常見)',
      GatlingGun_2: '加特林機槍 (少見)',
      GatlingGun_3: '加特林機槍 (稀有)',
      GatlingGun_4: '加特林機槍 (史詩)',
      GatlingGun_5: '加特林機槍 (傳奇)',
      Blueprint_GatlingGun_2: '加特林機槍設計圖1',
      Blueprint_GatlingGun_3: '加特林機槍設計圖2',
      Blueprint_GatlingGun_4: '加特林機槍設計圖3',
      Blueprint_GatlingGun_5: '加特林機槍設計圖4',
      GatlingGun_NPC: '加特林機槍 (NPC)',
      LaserGatlingGun: '激光加特林',
      GatlingBullet: '加特林子彈',
      FlameThrower: '火焰噴射器 (常見)',
      FlameThrower_2: '火焰噴射器 (少見)',
      FlameThrower_3: '火焰噴射器 (稀有)',
      FlameThrower_4: '火焰噴射器 (史詩)',
      FlameThrower_5: '火焰噴射器 (傳奇)',
      Blueprint_FlameThrower_2: '火焰放射器設計圖1',
      Blueprint_FlameThrower_3: '火焰放射器設計圖2',
      Blueprint_FlameThrower_4: '火焰放射器設計圖3',
      Blueprint_FlameThrower_5: '火焰放射器設計圖4',
      FlamethrowerBullet: '火焰放射器燃料',
      FlameThrower_NPC: '火焰噴射器 (NPC)',
      GrenadeLauncher: '榴彈發射器 (常見)',
      GrenadeLauncher_2: '榴彈發射器 (少見)',
      GrenadeLauncher_3: '榴彈發射器 (稀有)',
      GrenadeLauncher_4: '榴彈發射器 (史詩)',
      GrenadeLauncher_5: '榴彈發射器 (傳奇)',
      Blueprint_GrenadeLauncher_2: '榴彈發射器設計圖1',
      Blueprint_GrenadeLauncher_3: '榴彈發射器設計圖2',
      Blueprint_GrenadeLauncher_4: '榴彈發射器設計圖3',
      Blueprint_GrenadeLauncher_5: '榴彈發射器設計圖4',
      GrenadeBullet: '榴彈',
      GrenadeLauncher_NPC: '榴彈發射器 (NPC)',
      Launcher_Meteor: '隕石發射器',
      PlasticArmorWeight: '輕便塑鋼盔甲 (常見)',
      PlasticArmorWeight_2: '輕便塑鋼盔甲 (少見)',
      PlasticArmorWeight_3: '輕便塑鋼盔甲 (稀有)',
      PlasticArmorWeight_4: '輕便塑鋼盔甲 (史詩)',
      PlasticArmorWeight_5: '輕便塑鋼盔甲 (傳奇)',
      Blueprint_PlasticArmorWeight_2: '輕便塑鋼盔甲設計圖1',
      Blueprint_PlasticArmorWeight_3: '輕便塑鋼盔甲設計圖2',
      Blueprint_PlasticArmorWeight_4: '輕便塑鋼盔甲設計圖3',
      Blueprint_PlasticArmorWeight_5: '輕便塑鋼盔甲設計圖4',
      PlasticHelmet: '塑鋼頭盔 (常見)',
      PlasticHelmet_2: '塑鋼頭盔 (少見)',
      PlasticHelmet_3: '塑鋼頭盔 (稀有)',
      PlasticHelmet_4: '塑鋼頭盔 (史詩)',
      PlasticHelmet_5: '塑鋼頭盔 (傳奇)',
      Blueprint_PlasticHelmet_2: '塑鋼頭盔設計圖1',
      Blueprint_PlasticHelmet_3: '塑鋼頭盔設計圖2',
      Blueprint_PlasticHelmet_4: '塑鋼頭盔設計圖3',
      Blueprint_PlasticHelmet_5: '塑鋼頭盔設計圖4',
      PlasticArmorCold: '耐寒塑鋼盔甲 (常見)',
      PlasticArmorCold_2: '耐寒塑鋼盔甲 (少見)',
      PlasticArmorCold_3: '耐寒塑鋼盔甲 (稀有)',
      PlasticArmorCold_4: '耐寒塑鋼盔甲 (史詩)',
      PlasticArmorCold_5: '耐寒塑鋼盔甲 (傳奇)',
      Blueprint_PlasticArmorCold_2: '耐寒塑鋼盔甲設計圖1',
      Blueprint_PlasticArmorCold_3: '耐寒塑鋼盔甲設計圖2',
      Blueprint_PlasticArmorCold_4: '耐寒塑鋼盔甲設計圖3',
      Blueprint_PlasticArmorCold_5: '耐寒塑鋼盔甲設計圖4',
      PlasticArmorHeat: '耐熱塑鋼盔甲 (常見)',
      PlasticArmorHeat_2: '耐熱塑鋼盔甲 (少見)',
      PlasticArmorHeat_3: '耐熱塑鋼盔甲 (稀有)',
      PlasticArmorHeat_4: '耐熱塑鋼盔甲 (史詩)',
      PlasticArmorHeat_5: '耐熱塑鋼盔甲 (傳奇)',
      Blueprint_PlasticArmorHeat_2: '耐熱塑鋼盔甲設計圖1',
      Blueprint_PlasticArmorHeat_3: '耐熱塑鋼盔甲設計圖2',
      Blueprint_PlasticArmorHeat_4: '耐熱塑鋼盔甲設計圖3',
      Blueprint_PlasticArmorHeat_5: '耐熱塑鋼盔甲設計圖4',
      PalSummon_KingBahamut_Dragon: '歿殃的石板',
      PalSummon_KingBahamut_Dragon_Parts: '歿殃的石板碎片',
      PalSummon_KingBahamut_Dragon_2: '【極】歿殃的石板',
      PalSummon_KingBahamut_Dragon_Parts_2: '【極】歿殃的石板碎片',
      Elixir_weight_01: '巨人秘藥 (史詩)',
      Elixir_weight_02: '巨人秘藥 (傳奇)',
      Rankup_1: '萬能帕魯精華提取液☆1',
      Rankup_2: '萬能帕魯精華提取液☆2',
      Rankup_3: '萬能帕魯精華提取液☆3',
      Rankup_4: '萬能帕魯精華提取液☆4',
      Rankup_Arbitrary: '濃縮萬能帕魯精華',
      Elixir_attack_01: '猛擊秘藥',
      Elixir_attack_02: '猛擊靈藥',
      PoisonMushroom: '不可思議的蘑菇',
      MushroomJuice: '不可思議的蘑菇汁',
      Elixir_workspeed_01: '勤勉秘藥',
      Elixir_workspeed_02: '勤勉靈藥',
      Elixir_stamina_01: '活力秘藥',
      Elixir_stamina_02: '活力靈藥',
      Elixir_hp_01: '命脈秘藥',
      Elixir_hp_02: '命脈靈藥',
      Lotus_weight_01: '耐重之蓮（小）',
      Lotus_weight_02: '耐重之蓮（大）',
      DogCoin: '汪汪幣',
      Lotus_hp_01: '生命之蓮（小）',
      Lotus_hp_02: '生命之蓮（大）',
      MeteorDrop: '隕石碎片',
      Lotus_attack_01: '力量之蓮（小）',
      Lotus_attack_02: '力量之蓮（大）',
      Lotus_workspeed_01: '巧手之蓮（小）',
      Lotus_workspeed_02: '巧手之蓮（大）',
      Lotus_stamina_01: '耐力之蓮（小）',
      Lotus_stamina_02: '耐力之蓮（大）',
      PalItem_MopBaby: '毛撣兒的絨毛',
      HeadEquip023: '百合女王的髮飾',
      HeadEquip024: '綢笠蛾帽',
      HeadEquip025: '朋克蜥的兜帽',
      HeadEquip026: '勾魂魷帽子',
      HeadEquip027: '黑鴉隱士帽子',
      HeadEquip028: '姬小兔的髮飾',
      HeadEquip029: '棉悠悠頭套',
      HeadEquip030: '趴趴鯰頭套',
      HeadEquip031: '毛撣兒帽子',
      HeadEquip032: '雷鳴童子帽子',
      HeadEquip033: '搗蛋貓帽子',
      GYM_Head_Grass: '佐伊的帽子',
      GYM_Head_Electric: '阿克塞爾的帽子',
      GYM_Head_Forest: '莉莉的帽子',
      GYM_Head_Snow: '維克托的帽子',
      GYM_Head_Desert: '馬庫斯的帽子',
      GYM_Head_Sakurajima: '紗夜的帽子',
      UnlockEquipmentSlot_Accessory_01: '不可思議的飾品箱',
      UnlockEquipmentSlot_Accessory_02: '神秘的飾品箱',
      Accessory_MaxWeightUp_01: '搬運工指環',
      Accessory_MaxWeightUp_02: '搬運工指環+1',
      Accessory_MaxWeightUp_03: '搬運工指環+2',
      PalSphere_Ultimate: '究極帕魯球',
      SkillUnlock_KingBahamut_Dragon: '歿殃專用鞍具',
      SkillUnlock_WeaselDragon_Fire: '桃旋鼬專用鞍具',
      SkillUnlock_FeatherOstrich: '戰冠雀的鞍具',
      SkillUnlock_HadesBird_Electric: '雷鳴鳥專用鞍具',
      SkillUnlock_SkyDragon_Grass: '翠羽龍專用鞍具',
      SkillUnlock_MoonQueen: '輝月伊專用鞍具',
      SkillUnlock_MushroomDragon_Dark: '菇波專用鞍具',
      SkillUnlock_MushroomDragon: '菇咚專用鞍具',
      SkillUnlock_WhiteAlienDragon: '傑諾路達的專用鞍具',
      SkillUnlock_GuardianDog: '八雲犬的鞍具',
      SkillCard_FlameFunnel: '炎之技能果實：流火',
      SkillCard_HolyBlast: '技能果實：光擊陣',
      Unlock_Picking_Tier1: '簡易的開鎖工具',
      Unlock_Picking_Tier2: '高質量開鎖工具',
      Unlock_Picking_Tier3: '專家開鎖工具',
      MeteorBullet: '隕石彈',
      Blueprint_HeadEquip025_1: '朋克蜥的兜帽設計圖1',
      Blueprint_HeadEquip025_2: '朋克蜥的兜帽設計圖2',
      Blueprint_HeadEquip025_3: '朋克蜥的兜帽設計圖3',
      Blueprint_HeadEquip025_4: '朋克蜥的兜帽設計圖4',
      Blueprint_HeadEquip026_1: '勾魂魷帽子設計圖1',
      Blueprint_HeadEquip026_2: '勾魂魷帽子設計圖2',
      Blueprint_HeadEquip026_3: '勾魂魷帽子設計圖3',
      Blueprint_HeadEquip026_4: '勾魂魷帽子設計圖4',
      Blueprint_HeadEquip028_1: '姬小兔的發飾設計圖1',
      Blueprint_HeadEquip028_2: '姬小兔的發飾設計圖2',
      Blueprint_HeadEquip028_3: '姬小兔的發飾設計圖3',
      Blueprint_HeadEquip028_4: '姬小兔的發飾設計圖4',
      Blueprint_HeadEquip031_1: '毛撣兒帽子設計圖1',
      Blueprint_HeadEquip031_2: '毛撣兒帽子設計圖2',
      Blueprint_HeadEquip031_3: '毛撣兒帽子設計圖3',
      Blueprint_HeadEquip031_4: '毛撣兒帽子設計圖4',
      Blueprint_HeadEquip032_1: '雷鳴童子帽子設計圖1',
      Blueprint_HeadEquip032_2: '雷鳴童子帽子設計圖2',
      Blueprint_HeadEquip032_3: '雷鳴童子帽子設計圖3',
      Blueprint_HeadEquip032_4: '雷鳴童子帽子設計圖4',
      HeadEquip025_2: '朋克蜥的兜帽 (少見)',
      HeadEquip025_3: '朋克蜥的兜帽 (稀有)',
      HeadEquip025_4: '朋克蜥的兜帽 (史詩)',
      HeadEquip025_5: '朋克蜥的兜帽 (傳說)',
      HeadEquip026_2: '勾魂魷帽子 (少見)',
      HeadEquip026_3: '勾魂魷帽子 (稀有)',
      HeadEquip026_4: '勾魂魷帽子 (史詩)',
      HeadEquip026_5: '勾魂魷帽子 (傳說)',
      HeadEquip028_2: '姬小兔的發飾 (少見)',
      HeadEquip028_3: '姬小兔的發飾 (稀有)',
      HeadEquip028_4: '姬小兔的發飾 (史詩)',
      HeadEquip028_5: '姬小兔的發飾 (傳說)',
      HeadEquip031_2: '毛撣兒帽子 (少見)',
      HeadEquip031_3: '毛撣兒帽子 (稀有)',
      HeadEquip031_4: '毛撣兒帽子 (史詩)',
      HeadEquip031_5: '毛撣兒帽子 (傳說)',
      HeadEquip032_2: '雷鳴童子帽子 (少見)',
      HeadEquip032_3: '雷鳴童子帽子 (稀有)',
      HeadEquip032_4: '雷鳴童子帽子 (史詩)',
      HeadEquip032_5: '雷鳴童子帽子 (傳說)',
      HeadEquip041: '霸王之角',
    },
    ...{
      // 4月新更新
      ExpBoost_01: '修練之書 (小)',
      ExpBoost_02: '修練之書 (中)',
      ExpBoost_03: '修練之書 (大)',
      ExpBoost_04: '修練之書 (特大)',
      LvUP_01: '修練結晶',
      Fruit_attack_01: '剛力之果',
      Fruit__defense_01: '堅壁之果',
      Fruit_hp_01: '生命之果',
      Homeward: 'Homeward',
      PalSummon_NightLady: '貝菈諾娃的石板',
      PalSummon_NightLady_Dark: '貝菈露潔的石板',
      PalSummon_NightLady_Dark_2: '【極】貝菈露潔的石板',
      PalSummon_NightLady_Parts: '貝菈諾娃的石板碎片',
      PalSummon_NightLady_Dark_Parts: '貝菈露潔的石板碎片',
      PalSummon_NightLady_Dark_Parts_2: '【極】貝菈露潔的石板碎片',
      AncientParts2: 'AncientParts2',
      AncientTechnologyBook_G1: 'AncientTechnologyBook_G1',
      Potion_Low: 'Potion_Low',
      Potion: 'Potion',
      Potion_High: 'Potion_High',
      Accessory_TalentChecker: 'Accessory_TalentChecker',
      Accessory_Nonkilling: 'Accessory_Nonkilling',
    },
    ...{
      //武器
      Bat: '木棍 (常見)', //須找正確ID
      Bat2: '棒球棒 (常見)', //須找正確ID
      Torch: '攜帶型火炬 (常見)',
      Axe_Tier_00: '石斧 (常見)',
      Axe_Tier_01: '金屬斧 (常見)',
      Axe_Tier_02: '精鍊金屬斧 (常見)',
      Axe_Tier_03: '未知的斧頭 (常見) ',
      Pickaxe_Tier_00: '石製十字鎬 (常見)',
      Pickaxe_Tier_01: '金屬十字鎬 (常見)',
      Pickaxe_Tier_02: '精鍊金屬十字鎬 (常見)',
      Pickaxe_Tier_03: '未知的十字鎬 (常見) ',
      Spear: '石矛 (常見)',
      Spear_2: '金屬矛 (常見)',
      Spear_3: '精鍊金屬矛 (常見)',
      Spear_QueenBee: '女皇蜂法杖 (少見)',
      Spear_SoldierBee: '蜂兵之矛 (少見)',
      Spear_ForestBoss: '莉莉之矛 (稀有)',
      Sword: '劍 (常見)',
      MeatCutterKnife: '切肉刀 (常見)',
      ElecBaton: '電擊棒 (常見)',
      WeakerBow: '老舊的弓 (常見)',
      WeakerBow_2: '老舊的弓 (少見)',
      WeakerBow_3: '老舊的弓 (稀有)',
      WeakerBow_4: '老舊的弓 (史詩)',
      WeakerBow_5: '老舊的弓 (傳奇)',
      Bow_Poison: '毒之弓 (常見)',
      Bow_Fire: '火之弓 (常見)',
      Bow_Triple: '三連弓 (常見)',
      Bow_Fifth: '五連弓 (常見)',
      BowGun: '十字弓 (常見)',
      BowGun_2: '十字弓 (少見)',
      BowGun_3: '十字弓 (稀有)',
      BowGun_4: '十字弓 (史詩)',
      BowGun_5: '十字弓 (傳奇)',
      BowGun_Poison: '毒箭矢專用十字弓 (常見)',
      BowGun_Fire: '火箭矢專用十字弓 (常見)',
      MakeshiftHandgun: '劣質手槍 (常見)',
      HandGun_Default: '手槍 (常見)',
      HandGun_Default_2: '手槍 (少見)',
      HandGun_Default_3: '手槍 (稀有)',
      HandGun_Default_4: '手槍 (史詩)',
      HandGun_Default_5: '手槍 (傳奇)',
      DecalGun_1: '噴漆槍1 (常見)',
      DecalGun_2: '噴漆槍2 (常見)',
      DecalGun_3: '噴漆槍3 (常見)',
      DecalGun_4: '噴漆槍4 (常見)',
      DecalGun_5: '噴漆槍5 (常見)',
      GrapplingGun: '爪鉤槍 (常見)',
      GrapplingGun2: '高級爪鉤槍 (少見)',
      GrapplingGun3: '優級爪鉤槍 (稀有)',
      GrapplingGun4: '特級爪鉤槍 (史詩)',
      DoubleBarrelShotgun: '雙管散彈槍 (常見)',
      DoubleBarrelShotgun_1: '雙管散彈槍 (少見)',
      DoubleBarrelShotgun_2: '雙管散彈槍 (稀有)',
      DoubleBarrelShotgun_3: '雙管散彈槍 (史詩)',
      DoubleBarrelShotgun_4: '雙管散彈槍 (傳奇)',
      PumpActionShotgun: '泵動式散彈槍 (常見)',
      PumpActionShotgun_2: '泵動式散彈槍 (少見)',
      PumpActionShotgun_3: '泵動式散彈槍 (稀有)',
      PumpActionShotgun_4: '泵動式散彈槍 (史詩)',
      PumpActionShotgun_5: '泵動式散彈槍 (傳奇)',
      Musket: '鳥槍 (常見)',
      Musket_2: '鳥槍 (少見)',
      Musket_3: '鳥槍 (稀有)',
      Musket_4: '鳥槍 (史詩)',
      Musket_5: '鳥槍 (傳奇)',
      SingleShotRifle: '單發步槍 (常見)',
      // SingleShotRifle: '單發步槍 (少見)',
      // SingleShotRifle: '單發步槍 (稀有)',
      // SingleShotRifle: '單發步槍 (史詩)',
      // SingleShotRifle: '單發步槍 (傳奇)',
      AssaultRifle_Default1: '突擊步槍 (常見)',
      AssaultRifle_Default2: '突擊步槍 (少見)',
      AssaultRifle_Default3: '突擊步槍 (稀有)',
      AssaultRifle_Default4: '突擊步槍 (史詩)',
      AssaultRifle_Default5: '突擊步槍 (傳奇)',
      Launcher_Default: '火箭彈發射器 (常見)',
      Launcher_Default_2: '火箭彈發射器 (少見)',
      Launcher_Default_3: '火箭彈發射器 (稀有)',
      Launcher_Default_4: '火箭彈發射器 (史詩)',
      Launcher_Default_5: '火箭彈發射器 (傳奇)',
      Launcher_Meat: '人肉發射器 (常見) ',
      SphereLauncher_Once: '單發型帕魯球發射器 (常見)',
      SphereLauncher: '擴散型帕魯球發射器 (常見)',
      HomingSphereLauncher: '自動追蹤帕魯球發射器 (常見)',
      FragGrenade: '破片手榴彈 (常見)',
      FragGrenade_Fire: '燒夷手榴彈 (常見)',
      FragGrenade_Elec: '電擊手榴彈 (常見)',
      FragGrenade_Ice: '冰凍手榴彈 (常見)',

      // npcs
      Bat_NPC: '木棍 (NPC)',
      Handgun_NPC: '手槍 (NPC)',
      RocketLauncher_NPC: '火箭彈發射器 (NPC)',
      AssaultRifle_NPC: '突擊步槍 (NPC)',
      BowGun_NPC: '十字弓 (NPC)',
      Shotgun_NPC: '雙管散彈槍 (NPC)',
      FragGrenade_NPC: '破片手榴彈 (NPC)',

      // betas

      CaptureRope: '捕獲繩 (常見) ',
      PenguinLauncher: '企鵝發射器 (史詩) ',
      PV_AssaultRifle_Default1: 'PV預設的突擊步槍 (傳奇) ',
      SniperRifle_Default: '狙擊步槍 (常見) ',
      ThrowStone: '丟出的石頭 (常見) ',
      RecurveBow: '反曲弓 (常見) ',
      FishingRod_Old: '普通的釣竿 (常見) ',
      FishingRod_Good: '高級的釣竿 (常見) ',
      FishingRod_Super: '優級的釣竿 (常見) ',
      FishingRod_Legendary: '特級的釣竿 (常見) ',
      AirGrapplingGun: '空氣爪鉤槍 (常見) ',
    },
    ...{
      //帕魯球
      PalSphere: ' (帕魯球) (常見)',
      PalSphere_Mega: ' (高級帕魯球) (常見)',
      PalSphere_Giga: ' (優級帕魯球) (少見)',
      PalSphere_Tera: ' (特級帕魯球) (稀有)',
      PalSphere_Master: ' (大師帕魯球) (史詩)',
      PalSphere_Legend: ' (傳奇帕魯球) (傳奇)',
      PalSphere_Robbery: ' (雷達帕魯球) (少見)',
    },
    ...{
      //防具
      Shield_01: '普通護盾',
      Shield_02: '高級護盾',
      Shield_03: '優級護盾',
      Shield_04: '特級護盾',
      Shield_Ultra: '超級護盾',
      ClothArmor: '布衣 (常見)',
      ClothArmor_2: '布衣 (少見)',
      ClothArmor_3: '布衣 (稀有)',
      ClothArmor_4: '布衣 (史詩)',
      ClothArmor_5: '布衣 (傳奇)',
      FurArmor: '毛皮盔甲 (常見)',
      FurArmor_2: '毛皮盔甲 (少見)',
      FurArmor_3: '毛皮盔甲 (稀有)',
      FurArmor_4: '毛皮盔甲 (史詩)',
      FurArmor_5: '毛皮盔甲 (傳奇)',
      CopperArmor: '金屬盔甲 (常見)',
      CopperArmor_2: '金屬盔甲 (少見)',
      CopperArmor_3: '金屬盔甲 (稀有)',
      CopperArmor_4: '金屬盔甲 (史詩)',
      CopperArmor_5: '金屬盔甲 (傳奇)',
      IronArmor: '精鍊金屬盔甲 (常見)',
      IronArmor_2: '精鍊金屬盔甲 (少見)',
      IronArmor_3: '精鍊金屬盔甲 (稀有)',
      IronArmor_4: '精鍊金屬盔甲 (史詩)',
      IronArmor_5: '精鍊金屬盔甲 (傳奇)',
      ClothHat: '漁夫帽 (常見) ',
      FurHelmet: '羽毛髮飾 (常見)',
      FurHelmet_2: '羽毛髮飾 (少見)',
      FurHelmet_3: '羽毛髮飾 (稀有)',
      FurHelmet_4: '羽毛髮飾 (史詩)',
      FurHelmet_5: '羽毛髮飾 (傳奇)',
      CopperHelmet: '金屬頭盔 (常見)',
      CopperHelmet_2: '金屬頭盔 (少見)',
      CopperHelmet_3: '金屬頭盔 (稀有)',
      CopperHelmet_4: '金屬頭盔 (史詩)',
      CopperHelmet_5: '金屬頭盔 (傳奇)',
      IronHelmet: '精鍊金屬頭盔 (常見)',
      IronHelmet_2: '精鍊金屬頭盔 (少見)',
      IronHelmet_3: '精鍊金屬頭盔 (稀有)',
      IronHelmet_4: '精鍊金屬頭盔 (史詩)',
      IronHelmet_5: '精鍊金屬頭盔 (傳奇)',
      StealHelmet: '帕魯金屬頭盔 (常見)',
      StealHelmet_2: '帕魯金屬頭盔 (少見)',
      StealHelmet_3: '帕魯金屬頭盔 (稀有)',
      StealHelmet_4: '帕魯金屬頭盔 (史詩)',
      StealHelmet_5: '帕魯金屬頭盔 (傳奇)',
      StealArmor: '帕魯金屬盔甲 (常見)',
      StealArmor_2: '帕魯金屬盔甲 (少見)',
      StealArmor_3: '帕魯金屬盔甲 (稀有)',
      StealArmor_4: '帕魯金屬盔甲 (史詩)',
      StealArmor_5: '帕魯金屬盔甲 (傳奇)',
      Head001: '王冠 (常見)',
      Head001_2: '王冠 (少見)',
      Head001_3: '王冠 (稀有)',
      Head001_4: '王冠 (史詩)',
      Head001_5: '王冠 (傳奇)',
      Head002: '金色王冠 (常見)',
      Head002_2: '金色王冠 (少見)',
      Head002_3: '金色王冠 (稀有)',
      Head002_4: '金色王冠 (史詩)',
      Head002_5: '金色王冠 (傳奇)',
      Head003: '長耳髮箍 (常見)',
      Head003_2: '長耳髮箍 (少見)',
      Head003_3: '長耳髮箍 (稀有)',
      Head003_4: '長耳髮箍 (史詩)',
      Head003_5: '長耳髮箍 (傳奇)',
      Head004: '女巫帽 (常見)',
      Head004_2: '女巫帽 (少見)',
      Head004_3: '女巫帽 (稀有)',
      Head004_4: '女巫帽 (史詩)',
      Head004_5: '女巫帽 (傳奇)',
      Head005: '費多拉帽 (常見)',
      Head005_2: '費多拉帽 (少見)',
      Head005_3: '費多拉帽 (稀有)',
      Head005_4: '費多拉帽 (史詩)',
      Head005_5: '費多拉帽 (傳奇)',
      Head006: '安全帽 (常見)',
      Head006_2: '安全帽 (少見)',
      Head006_3: '安全帽 (稀有)',
      Head006_4: '安全帽 (史詩)',
      Head006_5: '安全帽 (傳奇)',
      Head007: '大禮帽 (常見)',
      Head007_2: '大禮帽 (少見)',
      Head007_3: '大禮帽 (稀有)',
      Head007_4: '大禮帽 (史詩)',
      Head007_5: '大禮帽 (傳奇)',
      Head008: '三角帽 (常見)',
      Head008_2: '三角帽 (少見)',
      Head008_3: '三角帽 (稀有)',
      Head008_4: '三角帽 (史詩)',
      Head008_5: '三角帽 (傳奇)',
      Head009: '探險帽 (常見)',
      Head009_2: '探險帽 (少見)',
      Head009_3: '探險帽 (稀有)',
      Head009_4: '探險帽 (史詩)',
      Head009_5: '探險帽 (傳奇)',
      Head010: '學士帽 (常見)',
      Head010_2: '學士帽 (少見)',
      Head010_3: '學士帽 (稀有)',
      Head010_4: '學士帽 (史詩)',
      Head010_5: '學士帽 (傳奇)',
      Head011: '農夫帽 (常見)',
      Head011_2: '農夫帽 (少見)',
      Head011_3: '農夫帽 (稀有)',
      Head011_4: '農夫帽 (史詩)',
      Head011_5: '農夫帽 (傳奇)',
      Head012: '博勒帽 (常見)',
      Head012_2: '博勒帽 (少見)',
      Head012_3: '博勒帽 (稀有)',
      Head012_4: '博勒帽 (史詩)',
      Head012_5: '博勒帽 (傳奇)',
      Head013: '炸蛋鳥帽 (常見)',
      Head013_2: '炸蛋鳥帽 (少見)',
      Head013_3: '炸蛋鳥帽 (稀有)',
      Head013_4: '炸蛋鳥帽 (史詩)',
      Head013_5: '炸蛋鳥帽 (傳奇)',
      Head014: '笑臉炸蛋鳥帽 (常見)',
      Head014_2: '笑臉炸蛋鳥帽 (少見)',
      Head014_3: '笑臉炸蛋鳥帽 (稀有)',
      Head014_4: '笑臉炸蛋鳥帽 (史詩)',
      Head014_5: '笑臉炸蛋鳥帽 (傳奇)',
      Head015: '葉泥泥帽 (常見)',
      Head015_2: '葉泥泥帽 (少見)',
      Head015_3: '葉泥泥帽 (稀有)',
      Head015_4: '葉泥泥帽 (史詩)',
      Head015_5: '葉泥泥帽 (傳奇)',
      Head016: '企丸王帽 (常見)',
      Head016_2: '企丸王帽 (少見)',
      Head016_3: '企丸王帽 (稀有)',
      Head016_4: '企丸王帽 (史詩)',
      Head016_5: '企丸王帽 (傳奇)',
      Head017: '闇巫貓帽 (常見)',
      Head017_2: '闇巫貓帽 (少見)',
      Head017_3: '闇巫貓帽 (稀有)',
      Head017_4: '闇巫貓帽 (史詩)',
      Head017_5: '闇巫貓帽 (傳奇)',
      ...{
        //須找正確ID
        ClothArmorHeat: '熱帶地區民族服裝 (常見)',
        ClothArmorHeat_2: '熱帶地區民族服裝 (少見)',
        ClothArmorHeat_3: '熱帶地區民族服裝 (稀有)',
        ClothArmorHeat_4: '熱帶地區民族服裝 (史詩)',
        ClothArmorHeat_5: '熱帶地區民族服裝 (傳奇)',
        ClothArmorCold: '寒冷地區民族服裝 (常見)',
        ClothArmorCold_2: '寒冷地區民族服裝 (少見)',
        ClothArmorCold_3: '寒冷地區民族服裝 (稀有)',
        ClothArmorCold_4: '寒冷地區民族服裝 (史詩)',
        ClothArmorCold_5: '寒冷地區民族服裝 (傳奇)',
        FurArmorHeat: '耐熱毛皮盔甲 (常見)',
        FurArmorHeat_2: '耐熱毛皮盔甲 (少見)',
        FurArmorHeat_3: '耐熱毛皮盔甲 (稀有)',
        FurArmorHeat_4: '耐熱毛皮盔甲 (史詩)',
        FurArmorHeat_5: '耐熱毛皮盔甲 (傳奇)',
        FurArmorCold: '耐寒毛皮盔甲 (常見)',
        FurArmorCold_2: '耐寒毛皮盔甲 (少見)',
        FurArmorCold_3: '耐寒毛皮盔甲 (稀有)',
        FurArmorCold_4: '耐寒毛皮盔甲 (史詩)',
        FurArmorCold_5: '耐寒毛皮盔甲 (傳奇)',
        CopperArmorHeat: '耐熱金屬盔甲 (常見)',
        CopperArmorHeat_2: '耐熱金屬盔甲 (少見)',
        CopperArmorHeat_3: '耐熱金屬盔甲 (稀有)',
        CopperArmorHeat_4: '耐熱金屬盔甲 (史詩)',
        CopperArmorHeat_5: '耐熱金屬盔甲 (傳奇)',
        CopperArmorCold: '耐寒金屬盔甲 (常見)',
        CopperArmorCold_2: '耐寒金屬盔甲 (少見)',
        CopperArmorCold_3: '耐寒金屬盔甲 (稀有)',
        CopperArmorCold_4: '耐寒金屬盔甲 (史詩)',
        CopperArmorCold_5: '耐寒金屬盔甲 (傳奇)',
        IronArmorHeat: '耐熱精鍊金屬盔甲 (常見)',
        IronArmorHeat_2: '耐熱精鍊金屬盔甲 (少見)',
        IronArmorHeat_3: '耐熱精鍊金屬盔甲 (稀有)',
        IronArmorHeat_4: '耐熱精鍊金屬盔甲 (史詩)',
        IronArmorHeat_5: '耐熱精鍊金屬盔甲 (傳奇)',
        IronArmorCold: '耐寒精鍊金屬盔甲 (常見)',
        IronArmorCold_2: '耐寒精鍊金屬盔甲 (少見)',
        IronArmorCold_3: '耐寒精鍊金屬盔甲 (稀有)',
        IronArmorCold_4: '耐寒精鍊金屬盔甲 (史詩)',
        IronArmorCold_5: '耐寒精鍊金屬盔甲 (傳奇)',
        StealArmorHeat: '耐熱帕魯金屬盔甲 (常見)',
        StealArmorHeat_2: '耐熱帕魯金屬盔甲 (少見)',
        StealArmorHeat_3: '耐熱帕魯金屬盔甲 (稀有)',
        StealArmorHeat_4: '耐熱帕魯金屬盔甲 (史詩)',
        StealArmorHeat_5: '耐熱帕魯金屬盔甲 (傳奇)',
        StealArmorCold: '耐寒帕魯金屬盔甲 (常見)',
        StealArmorCold_2: '耐寒帕魯金屬盔甲 (少見)',
        StealArmorCold_3: '耐寒帕魯金屬盔甲 (稀有)',
        StealArmorCold_4: '耐寒帕魯金屬盔甲 (史詩)',
        StealArmorCold_5: '耐寒帕魯金屬盔甲 (傳奇)',
      },
    },
    ...{
      //飾品
      Accessory_HP_1: '生命吊墜 (常見)',
      Accessory_HP_2: '生命吊墜+1 (少見)',
      Accessory_HP_3: '生命吊墜+2 (稀有)',
      Accessory_AT_1: '攻擊吊墜 (常見)',
      Accessory_AT_2: '攻擊吊墜+1 (少見)',
      Accessory_AT_3: '攻擊吊墜+2 (稀有)',
      Accessory_defense_1: '防禦吊墜 (常見)',
      Accessory_defense_2: '防禦吊墜+1 (稀有)',
      Accessory_defense_3: '防禦吊墜+2 (少見)',
      Accessory_WorkSpeed_1: '勤奮吊墜 (常見)',
      Accessory_WorkSpeed_2: '勤奮吊墜+1 (少見)',
      Accessory_WorkSpeed_3: '勤奮吊墜+2 (稀有)',
      Accessory_HeatResist_1: '防暑內衣 (常見)',
      Accessory_HeatResist_2: '防暑內衣+1 (少見)',
      Accessory_HeatResist_3: '防暑內衣+2 (稀有)',
      Accessory_CoolResist_1: '防寒內衣 (常見)',
      Accessory_CoolResist_2: '防寒內衣+1 (少見)',
      Accessory_CoolResist_3: '防寒內衣+2 (稀有)',
      Accessory_NormalResist_1: '抗無屬性戒指 (常見)',
      Accessory_NormalResist_2: '抗無屬性戒指+1 (少見)',
      Accessory_NormalResist_3: '抗無屬性戒指+2 (稀有)',
      Accessory_FireResist_1: '抗火屬性戒指 (常見)',
      Accessory_FireResist_2: '抗火屬性戒指+1 (少見)',
      Accessory_FireResist_3: '抗火屬性戒指+2 (稀有)',
      Accessory_AquaResist_1: '抗水屬性戒指 (常見)',
      Accessory_AquaResist_2: '抗水屬性戒指+1 (少見)',
      Accessory_AquaResist_3: '抗水屬性戒指+2 (稀有)',
      Accessory_ThunderResist_1: '抗雷屬性戒指 (常見)',
      Accessory_ThunderResist_2: '抗雷屬性戒指+1 (少見)',
      Accessory_ThunderResist_3: '抗雷屬性戒指+2 (稀有)',
      Accessory_LeafResist_1: '抗草屬性戒指 (常見)',
      Accessory_LeafResist_2: '抗草屬性戒指+1 (少見)',
      Accessory_LeafResist_3: '抗草屬性戒指+2 (稀有)',
      Accessory_IceResist_1: '抗冰屬性戒指 (常見)',
      Accessory_IceResist_2: '抗冰屬性戒指+1 (少見)',
      Accessory_IceResist_3: '抗冰屬性戒指+2 (稀有)',
      Accessory_EarthResist_1: '抗地屬性戒指 (常見)',
      Accessory_EarthResist_2: '抗地屬性戒指+1 (少見)',
      Accessory_EarthResist_3: '抗地屬性戒指+2 (稀有)',
      Accessory_DarkResist_1: '抗暗屬性戒指 (常見)',
      Accessory_DarkResist_2: '抗暗屬性戒指+1 (少見)',
      Accessory_DarkResist_3: '抗暗屬性戒指+2 (稀有)',
      Accessory_DragonResist_1: '抗龍屬性戒指 (常見)',
      Accessory_DragonResist_2: '抗龍屬性戒指+1 (少見)',
      Accessory_DragonResist_3: '抗龍屬性戒指+2 (稀有)',
      Accessory_Nonkilling: '手下留情之戒 (常見)',
      Accessory_TalentChecker: '才能眼鏡 (常見)',
      ClawsPendant: '利爪吊墜 (常見) ',
      FangNecklace: '方項鍊 (常見) ',
      NightVisionGoggles: '夜視鏡 (常見) ',
      GasMask: '防毒面具 (常見) ',
    },

    ...{
      //素材
      Money: '金幣 (常見)',
      Wood: '木材 (常見)',
      Fiber: '纖維 (常見)',
      Stone: '石頭 (常見)',
      Pal_crystal_S: '帕魯礦碎片 (常見)',
      CopperOre: '金屬礦石 (常見)',
      Coal: '石炭 (常見)',
      Sulfur: '硫磺 (常見)',
      Quartz: '純水晶 (常見)',
      Wool: '羊毛 (常見)',
      Leather: '皮革 (常見)',
      Bone: '骨頭 (常見)',
      Horn: '角 (常見)',
      ElectricOrgan: '發電器官 (常見)',
      Venom: '毒腺 (常見)',
      FireOrgan: '噴火器官 (常見)',
      IceOrgan: '結冰器官 (常見)',
      PalFluid: '帕魯體液 (常見)',
      PalItem_ColorfulBird: '炸蛋鳥的羽毛 (常見)', //須找正確ID
      PalItem_PlantSlime: '葉泥泥的葉子 (常見)', //須找正確ID
      PalItem_CaptainPenguin: '企丸王的羽毛裝飾 (常見)', //須找正確ID
      PalItem_CatMage: '闇巫貓的體毛 (常見)', //須找正確ID
      PalOil: '優質帕魯油 (少見)',
      Unko_S: '糞便 (常見)',
      Unko_L: '大坨糞便 (常見)',
      PalCrystal_Ex: '古代文明部件 (稀有)',
      BerrySeeds: '莓果種子 (常見)',
      TomatoSeeds: '蕃茄種子 (常見)',
      LettuceSeeds: '萵苣種子 (常見)',
      WheatSeeds: '小麥種子 (常見)',
      Cloth: '布 (常見)',
      Cloth2: '優質布 (少見)',
      MachineParts: '釘子 (常見)',
      Gunpowder2: '火藥 (常見)',
      MachineParts2: '電路板 (常見)',
      Polymer: '聚合物 (常見)',
      Silicon: '矽 (常見)',
      Cement: '水泥 (常見)',
      CarbonFiber: '碳纖維 (常見)',
      Charcoal: '木炭 (常見)',
      CopperIngot: '金屬錠 (常見)',
      IronIngot: '精鍊金屬錠 (常見)',
      StealIngot: '帕魯金屬錠 (常見)',
      Flour: '麵粉 (常見)',
      PalEgg_Normal_01: '平凡帕魯蛋 (常見)',
      PalEgg_Normal_02: '平凡帕魯蛋 (常見)',
      PalEgg_Normal_03: '大型平凡帕魯蛋 (少見)',
      PalEgg_Normal_04: '大型平凡帕魯蛋 (少見)',
      PalEgg_Normal_05: '巨大平凡帕魯蛋 (稀有)',
      PalEgg_Fire_01: '火熱帕魯蛋 (常見)',
      PalEgg_Fire_02: '火熱帕魯蛋 (常見)',
      PalEgg_Fire_03: '大型火熱帕魯蛋 (少見)',
      PalEgg_Fire_04: '大型火熱帕魯蛋 (少見)',
      PalEgg_Fire_05: '巨大火熱帕魯蛋 (稀有)',
      PalEgg_Water_01: '潤澤帕魯蛋 (常見)',
      PalEgg_Water_02: '潤澤帕魯蛋 (常見)',
      PalEgg_Water_03: '大型潤澤帕魯蛋 (少見)',
      PalEgg_Water_04: '大型潤澤帕魯蛋 (少見)',
      PalEgg_Water_05: '巨大潤澤帕魯蛋 (稀有)',
      PalEgg_Leaf_01: '新綠帕魯蛋 (常見)',
      PalEgg_Leaf_02: '新綠帕魯蛋 (常見)',
      PalEgg_Leaf_03: '大型新綠帕魯蛋 (少見)',
      PalEgg_Leaf_04: '大型新綠帕魯蛋 (少見)',
      PalEgg_Leaf_05: '巨大新綠帕魯蛋 (稀有)',
      PalEgg_Electricity_01: '電氣帕魯蛋 (常見)',
      PalEgg_Electricity_02: '電氣帕魯蛋 (常見)',
      PalEgg_Electricity_03: '大型電氣帕魯蛋 (少見)',
      PalEgg_Electricity_04: '大型電氣帕魯蛋 (少見)',
      PalEgg_Electricity_05: '巨大電氣帕魯蛋 (稀有)',
      PalEgg_Ice_01: '冰冷帕魯蛋 (常見)',
      PalEgg_Ice_02: '冰冷帕魯蛋 (常見)',
      PalEgg_Ice_03: '大型冰冷帕魯蛋 (少見)',
      PalEgg_Ice_04: '大型冰冷帕魯蛋 (少見)',
      PalEgg_Ice_05: '巨大冰冷帕魯蛋 (稀有)',
      PalEgg_Earth_01: '粗糙帕魯蛋 (常見)',
      PalEgg_Earth_02: '粗糙帕魯蛋 (常見)',
      PalEgg_Earth_03: '大型粗糙帕魯蛋 (少見)',
      PalEgg_Earth_04: '大型粗糙帕魯蛋 (少見)',
      PalEgg_Earth_05: '巨大粗糙帕魯蛋 (稀有)',
      PalEgg_Dark_01: '暗黑帕魯蛋 (常見)',
      PalEgg_Dark_02: '暗黑帕魯蛋 (常見)',
      PalEgg_Dark_03: '大型暗黑帕魯蛋 (少見)',
      PalEgg_Dark_04: '大型暗黑帕魯蛋 (少見)',
      PalEgg_Dark_05: '巨大暗黑帕魯蛋 (稀有)',
      PalEgg_Dragon_01: '龍息帕魯蛋 (常見)',
      PalEgg_Dragon_02: '龍息帕魯蛋 (常見)',
      PalEgg_Dragon_03: '大型龍息帕魯蛋 (少見)',
      PalEgg_Dragon_04: '大型龍息帕魯蛋 (少見)',
      PalEgg_Dragon_05: '巨大龍息帕魯蛋 (稀有)',
      Ruby: '紅寶石 (稀有)',
      Sapphire: '藍寶石 (稀有)',
      Eemerald: '祖母綠 (史詩)',
      Diamond: '鑽石 (史詩)',
      PalItem_ToSell_01: '貴重的龍珠 (稀有)',
      PalItem_ToSell_02: '貴重的羽毛 (稀有)',
      PalItem_ToSell_03: '貴重的內臟 (稀有)',
      PalItem_ToSell_04: '貴重的利爪 (稀有)',
      PalItem_ToSell_05: '貴重的獸毛 (稀有)',
      PalUpgradeStone: '小型帕魯之魂 (少見)',
      PalUpgradeStone2: '中等帕魯之魂 (稀有)',
      PalUpgradeStone3: '大型帕魯之魂 (史詩)',
      AnimalSkin: '動物的皮 (常見) ',
      AnimalSkin2: '動物的皮 (少見) ',
      Scales: '動物的麟 (常見) ',
      Scales2: '動物的麟 (少見) ',
      Claws: '動物的爪 (常見) ',
      Claws2: '動物的爪 (少見) ',
      ElectronicCircuit: '電路板 (常見) ',
      Fang: '方 (常見) ',
      Fang2: '方 (少見) ',
      Flint: '燧石 (常見) ',
      Gunpowder: '火藥 (常見) ',
      IronOre: '鐵礦 (常見) ',
      Kitsunebi_Fire: '狐火 (常見) ',
      Leather2: '皮革 (少見) ',
      Sharkkid_Scale: '鯊魚小子的鱗片 (稀有) ',
      Pal_crystal_L: '帕魯礦 (常見)',
      PAL_Growth_Stone_S: '小的帕魯成長石 (常見) ',
      PAL_Growth_Stone_M: '中的帕魯成長石 (常見) ',
      PAL_Growth_Stone_L: '大的帕魯成長石 (常見) ',
      PAL_Growth_Stone_XL: '巨大的帕魯成長石 (常見) ',
      PotatoSeedPotatoes: '馬鈴薯種子 (常見) ',
      CrudeOil: '原油 (常見)',
      Plastic: '塑膠 (常見) ',
      Computer: '電腦 (常見) ',
      CashFang: '現金坊 (常見) ',
      CashScales: '現金磅 (常見) ',
      Sand: '沙 (少見) ',
    },
    ...{
      //消耗品
      SkillCard_PowerShot: '技能果實：能量射擊 (少見)',
      SkillCard_PowerBall: '技能果實：元氣彈 (稀有)',
      SkillCard_HyperBeam: '技能果實：帕魯光束 (史詩)',
      SkillCard_AirCanon: '技能果實：空氣砲 (少見)',
      SkillCard_SelfDestruct: '技能果實：自爆 (史詩)',
      SkillCard_WindCutter: '草屬技能果實：風刃 (少見)',
      SkillCard_GrassTornado: '草屬技能果實：綠野颶風 (稀有)',
      SkillCard_SolarBeam: '草屬技能果實：太陽光束 (史詩)',
      SkillCard_SeedMachinegun: '草屬技能果實：種子機關槍 (少見)',
      SkillCard_RootAttack: '草屬技能果實：纏繞地刺 (稀有)',
      SkillCard_SeedMine: '草屬技能果實：種子地雷 (少見)',
      SkillCard_WaterGun: '水屬技能果實：水槍 (少見)',
      SkillCard_WaterBall: '水屬技能果實：爆裂水球 (稀有)',
      SkillCard_HydroPump: '水屬技能果實：高壓水炮 (史詩)',
      SkillCard_AquaJet: '水屬技能果實：水流射擊 (少見)',
      SkillCard_BubbleShot: '水屬技能果實：泡沫射擊 (稀有)',
      SkillCard_AcidRain: '水屬技能果實：酸雨 (少見)',
      SkillCard_FireBlast: '火屬技能果實：烈焰射擊 (少見)',
      SkillCard_Flamethrower: '火屬技能果實：烈焰放射 (稀有)',
      SkillCard_FireBall: '火屬技能果實：烈焰球 (史詩)',
      SkillCard_FlareArrow: '火屬技能果實：烈焰箭 (少見)',
      SkillCard_FireSeed: '火屬技能果實：烈焰濺射 (少見)',
      SkillCard_Inferno: '火屬技能果實：地獄火 (史詩)',
      SkillCard_FlareTornado: '火屬技能果實：烈焰風暴 (稀有)',
      SkillCard_ElecWave: '雷屬技能果實：沖擊波 (少見)',
      SkillCard_Thunderbolt: '雷屬技能果實：閃電伏特 (史詩)',
      SkillCard_LineThunder: '雷屬技能果實：雷擊 (稀有)',
      SkillCard_ThunderFunnel: '雷屬技能果實：等離子浮游砲 (少見)',
      SkillCard_SpreadPulse: '雷屬技能果實：電火花 (少見)',
      SkillCard_LockonLaser: '雷屬技能果實：鎖定雷射 (稀有)',
      SkillCard_ThunderBall: '雷屬技能果實：閃電球 (少見)',
      SkillCard_ThreeThunder: '雷屬技能果實：三重雷擊 (稀有)',
      SkillCard_LightningStrike: '雷屬技能果實：閃電衝擊 (史詩)',
      SkillCard_ThrowRock: '地屬技能果實：投石 (少見)',
      SkillCard_SandTornado: '地屬技能果實：沙塵旋風 (稀有)',
      SkillCard_RockLance: '地屬技能果實：岩石銳矛 (史詩)',
      SkillCard_MudShot: '地屬技能果實：泥漿投擲 (少見)',
      SkillCard_StoneShotgun: '地屬技能果實：碎石霰彈 (少見)',
      SkillCard_IceMissile: '冰屬技能果實：冰雪飛彈 (少見)',
      SkillCard_BlizzardLance: '冰屬技能果實：冰刺 (稀有)',
      SkillCard_IcicleThrow: '冰屬技能果實：鉆石星辰 (史詩)',
      SkillCard_IceBlade: '冰屬技能果實：冰刃 (少見)',
      SkillCard_FrostBreath: '冰屬技能果實：凜冬之息 (稀有)',
      SkillCard_DarkWave: '暗屬技能果實：暗影波動 (少見)',
      SkillCard_ShadowBall: '暗屬技能果實：惡夢球 (稀有)',
      SkillCard_Psychokinesis: '暗屬技能果實：念動引力 (史詩)',
      SkillCard_PoisonShot: '暗屬技能果實：劇毒射擊 (少見)',
      SkillCard_GhostFlame: '暗屬技能果實：鬼火 (少見)',
      SkillCard_DarkLaser: '暗屬技能果實：暗黑鐳射 (史詩)',
      SkillCard_DragonBreath: '龍屬技能果實：龍息 (稀有)',
      SkillCard_DragonCanon: '龍屬技能果實：龍息彈 (少見)',
      SkillCard_DragonWave: '龍屬技能果實：龍之波動 (稀有)',
      SkillCard_DragonMeteor: '龍屬技能果實：龍彗星 (史詩)',
      TechnologyBook_G1: '先進技術書籍 (科技點+1) (少見)',
      TechnologyBook_G2: '革新技術書籍 (科技點+2) (稀有)',
      TechnologyBook_G3: '未來技術書籍 (科技點+3) (史詩)',
      TreasureBoxKey01: '青銅鑰匙 (少見)',
      TreasureBoxKey02: '白銀鑰匙 (稀有)',
      TreasureBoxKey03: '黃金鑰匙 (史詩)',
      RepairKit: '修理工具組 (常見)',
      EnergyDrink: '能量飲料 (常見) ',
      FarmCrop_Tmp: 'TMP作物 (常見) ',
      Seed_Tmp: 'TMP種子 (常見) ',
      WaterBucket: '水桶 (常見) ',
      Antibiotic_Normal: '普通抗生素 (常見) ',
      Antibiotic_Good: '高級抗生素 (常見) ',
      Antibiotic_Super: '優級抗生素 (常見) ',
      MateItem01: '死亡物品 (常見) ',
      PalSummon: '帕魯召喚 (常見) ',
    },

    ...{
      //彈藥
      Arrow: '箭矢 (常見)',
      Arrow_Poison: '毒箭矢 (常見)',
      Arrow_Fire: '火箭矢 (常見)',
      RoughBullet: '劣質彈藥 (常見)',
      HandgunBullet: '手槍子彈 (常見)',
      MagnumBullet: '麥格農子彈 (常見)',
      RifleBullet: '步槍子彈 (常見)',
      ShotgunBullet: '散彈槍子彈 (常見)',
      MachingunBullet: '機關槍子彈 (常見)',
      AssaultRifleBullet: '突擊步槍子彈 (常見)',
      ExplosiveBullet: '火箭彈 (常見)',
      InkBullet: '噴漆顏料彈 (常見)',
      SmallBullet: '小子彈 (常見) ',
      LargeBullet: '大子彈 (常見) ',
    },
    ...{
      //食材
      Berries: '紅色莓果 (常見)',
      Mushroom: '蘑菇 (常見)',
      Meat_ChickenPal: '皮皮雞肉 (常見)', //須找正確ID
      Meat_SheepBall: '棉悠悠羊肉 (常見)', //須找正確ID
      Meat_Kelpie: '水靈兒魚肉 (常見)', //須找正確ID
      Meat_Eagle: '天擒鳥肉 (常見)', //須找正確ID
      Meat_Boar: '草莽豬肉 (常見)', //須找正確ID
      Meat_LazyCatfish: '趴趴鯰肉 (常見)', //須找正確ID
      Meat_Deer: '紫霞鹿肉 (常見)', //須找正確ID
      Meat_IceDeer: '嚴冬鹿肉 (常見)', //須找正確ID
      Meat_BerryGoat: '灌木羊香草肉 (常見)', //須找正確ID
      Meat_CowPal: '波霸牛肉 (常見)', //須找正確ID
      Meat_SakuraSaurus: '連理龍肉 (少見)', //須找正確ID
      Meat_GrassMammoth: '森猛獁獸肉 (少見)', //須找正確ID
      Meat: '生肉 (常見)',
      Egg: '蛋 (常見)',
      Milk: '牛奶 (常見)',
      Honey: '蜂蜜 (常見)', //須找正確ID
      Sweet: '棉花糖 (常見)', //須找正確ID
      Wheat: '小麥 (常見)',
      Tomato: '蕃茄 (常見)',
      Lettuce: '萵苣 (常見)',
      BakedMeat_ChickenPal: '烤皮皮雞 (常見)', //須找正確ID
      BakedMeat_SheepBall: '棉悠悠羊肉串烤 (常見)', //須找正確ID
      BakedMeat_Kelpie: '炭烤水靈兒 (常見)', //須找正確ID
      BakedMeat_Eagle: '炙燒天擒鳥 (常見)', //須找正確ID
      BakedMeat_Boar: '烤草莽豬 (常見)', //須找正確ID
      BakedMeat_LazyCatfish: '蒲燒趴趴鯰 (常見)', //須找正確ID
      BakedMeat_Deer: '炙烤紫霞鹿肉 (常見)', //須找正確ID
      BakedMeat_IceDeer: '炙烤嚴冬鹿肉 (常見)', //須找正確ID
      BakedMeat_BerryGoat: '香草烤灌木羊 (常見)', //須找正確ID
      BakedMeat_CowPal: '波霸牛排 (常見)', //須找正確ID
      BakedMeat_SakuraSaurus: '炙烤帶骨連理龍肉 (少見)', //須找正確ID
      BakedMeat_GrassMammoth: '森猛獁獸排 (少見)', //須找正確ID
      ChickenSaute: '香煎皮皮雞 (少見)', //須找正確ID
      GrilledSheepHerbs: '香草烤棉悠悠 (少見)', //須找正確ID
      GenghisKhan: '棉悠悠成吉思汗烤肉 (少見)', //須找正確ID
      Eaglestew: '燉煮天擒鳥肉 (少見)', //須找正確ID
      BaconEggs: '草莽豬培根蛋 (少見)', //須找正確ID
      StewedIceDeer: '嚴冬鹿肉燉菜 (少見)', //須找正確ID
      FriedChicken: '日式炸皮皮雞 (稀有)', //須找正確ID
      HotDog_2: '草莽豬熱狗 (稀有)', //須找正確ID
      DeerLocoMoco: '夏威夷紫霞鹿漢堡排飯 (稀有)', //須找正確ID
      DeerStew: '紫霞鹿肉燉菜 (稀有)', //須找正確ID
      Hamburger_2: '波霸牛漢堡 (稀有)', //須找正確ID
      Cheeseburger_2: '波霸牛起司漢堡 (稀有)', //須找正確ID
      FriedKelpie: '炸水靈兒 (稀有)', //須找正確ID
      Chowder: '趴趴鯰巧達濃湯 (稀有)', //須找正確ID
      GrilledMeat: '烤肉 (常見)', //須找正確ID
      Baked_Berries: '烤莓果 (常見)',
      BakedMushroom: '烤蘑菇 (常見)',
      Pan: '麵包 (Pan)',
      FriedEggs: '荷包蛋 (常見)',
      HotMilk: '熱牛奶 (常見)',
      JamBun: '果醬麵包 (常見)',
      Salad: '沙拉 (常見)',
      Omelet: '歐姆蛋 (常見)',
      FriedVegetables: '清炒蔬菜 (常見)',
      HotDog: '熱狗 (常見)',
      Pancake: '鬆餅 (常見)',
      MarinatedMushrooms: '醃蘑菇 (常見)',
      MushroomSoup: '蘑菇湯 (常見)',
      Carbonara: '義式培根蛋黃麵 (常見)',
      BLT: '墨西哥捲餅 (常見)',
      CheeseBurger: '起司漢堡 (常見)',
      Pizza: '披薩 (常見)',
      MeatSauce: '肉醬 (常見)',
      MushroomStew: '蘑菇燉菜 (常見)',
      Hamburger: '漢堡 (常見)',
      Cake: '蛋糕 (常見)',
      Herbs: '劣質藥品 (常見)', //須找正確ID
      Potion_Low: '普通藥水 (常見) ', //須找正確ID
      Medicines: '藥品 (常見)', //須找正確ID
      Potion: '高級藥水 (常見) ', //須找正確ID
      LuxuryMedicines: '高級藥品 (常見)', //須找正確ID
      Potion_High: '優級藥水 (常見) ', //須找正確ID
      MindControlDrug: '洗腦藥 (常見)',
      Poppy: '美麗花朵 (常見)',
      Opium: '可疑果汁 (常見)',
      Narcotic: '怪異果汁 (常見)',
      StatusPointResetSan: '消除記憶藥 (常見)',
      Berries2: '莓果 (少見) ',
      FishMeat: '魚肉 (常見) ',
      FishMeat2: '魚肉 (少見) ',
      Meat2: '生肉 (少見) ',
      VenisonBoiledInTomato: '番茄煮鹿肉 (常見) ',
      Potato: '馬鈴薯 (常見) ',
      Corn: '玉米 (常見) ',
      Pumpkin: '南瓜 (常見) ',
      Baked_Potato: '烤馬鈴薯 (常見) ',
      Grape: '葡萄 (常見) ',
      Hop: '啤酒花 (常見) ',
      Potage: '湯 (常見) ',
      Curry: '咖哩 (常見)',
      Sandwich: '三明治 (常見) ',
      CornSoup: '玉米湯 (常見) ',
      Stew: '炖菜 (常見) ',
      GrilledFish: '烤魚 (常見) ',
      SeafoodSoup: '海鮮湯 (常見) ',
      LuxuryOmelette: '豪華煎蛋捲 (常見) ',
      Beer: '啤酒 (常見) ',
      Wine: '葡萄酒 (常見) ',
    },

    ...{
      //重要物品
      Relic: '翠葉鼠雕像 (少見)',
      Lantern: '掛腰燈籠 (少見)',
      AutoMealPouch_Tier1: '小型飼料袋 (常見)',
      AutoMealPouch_Tier2: '中等飼料袋 (少見)',
      AutoMealPouch_Tier3: '大型飼料袋 (稀有)',
      AutoMealPouch_Tier4: '巨大飼料袋 (史詩)',
      AutoMealPouch_Tier5: '特大飼料袋 (傳奇)',
      SkillUnlock_Hedgehog_Ice: '冰刺鼠專用手套 (少見)', //須找正確ID
      SkillUnlock_MopKing: '毛老爹專用鞍具 (少見)',
      SkillUnlock_Hedgehog: '電棘鼠專用手套 (少見)', //須找正確ID
      SkillUnlock_Kitsunebi: '火絨狐專用背帶 (少見)',
      SkillUnlock_Alpaca: '美露帕專用鞍具 (少見)',
      SkillUnlock_Boar: '草莽豬專用鞍具 (少見)',
      SkillUnlock_FlyingManta: '魯米兒專用手套 (少見)',
      SkillUnlock_Carbunclo: '翠葉鼠專用衝鋒槍 (少見)',
      SkillUnlock_Garm: '獵狼專用附鞍具背帶 (少見)',
      SkillUnlock_Monkey: '新葉猿專用突擊步槍 (少見)',
      SkillUnlock_Serpent_Ground: '流沙蛇專用鞍具 (少見)', //須找正確ID
      SkillUnlock_Serpent: '滑水蛇專用鞍具 (少見)', //須找正確ID
      SkillUnlock_Deer_Ground: '祇岳鹿專用鞍具 (少見)', //須找正確ID
      SkillUnlock_Deer: '紫霞鹿專用鞍具 (少見)', //須找正確ID
      SkillUnlock_NaughtyCat: '笑魘猫專用鞍具 (少見)',
      SkillUnlock_Kirin: '雷角馬專用鞍具 (稀有)',
      SkillUnlock_NegativeOctopus: '勾魂魷專用手套 (稀有)',
      SkillUnlock_ColorfulBird: '炸蛋鳥專用手套 (稀有)',
      SkillUnlock_HawkBird: '疾風隼專用鞍具 (稀有)',
      SkillUnlock_FlameBuffalo: '熾焰牛專用鞍具 (稀有)',
      SkillUnlock_FlowerRabbit: '波娜兔專用項圈 (稀有)',
      SkillUnlock_DrillGame: '碎岩龜專用頭帶 (稀有)',
      SkillUnlock_Penguin: '企丸丸專用火箭彈發射器 (稀有)',
      SkillUnlock_FlowerDinosaur_Electric: '雷冠龍專用鞍具 (稀有)', //須找正確ID
      SkillUnlock_FlowerDinosaur: '花冠龍專用鞍具 (稀有)', //須找正確ID
      SkillUnlock_DreamDemon: '寐魔專用項圈 (稀有)',
      SkillUnlock_SakuraSaurus_Water: '海誓龍專用鞍具 (稀有)', //須找正確ID
      SkillUnlock_SakuraSaurus: '連理龍專用鞍具 (稀有)', //須找正確ID
      SkillUnlock_BirdDragon: '烽歌龍專用鞍具 (稀有)',
      SkillUnlock_BirdDragon_Ice: '霜歌龍專用鞍具 (稀有)', //須找正確ID
      SkillUnlock_WindChimes_Ice: '冰縛靈專用手套 (稀有)', //須找正確ID
      SkillUnlock_WeaselDragon: '疾旋鼬專用鞍具 (稀有)',
      SkillUnlock_WindChimes: '吊縛靈專用手套 (稀有)',
      SkillUnlock_KingAlpaca_Ice: '冰帝美露帕專用鞍具 (稀有)',
      SkillUnlock_KingAlpaca: '君王美露帕專用鞍具 (稀有)',
      SkillUnlock_FairyDragon_Water: '水靈龍專用鞍具 (稀有)', //須找正確ID
      SkillUnlock_FairyDragon: '精靈龍專用鞍具 (稀有)', //須找正確ID
      SkillUnlock_RaijinDaughter: '雷鳴童子專用項圈 (稀有)',
      SkillUnlock_Eagle: '天擒鳥專用手套 (稀有)',
      SkillUnlock_GhostBeast: '噬魂獸專用鞍具 (稀有)',
      SkillUnlock_GrassPanda_Electric: '雷胖達專用手榴彈發射器 (史詩)',
      SkillUnlock_GrassPanda: '葉胖達專用榴彈發射器 (史詩)',
      SkillUnlock_VolcanicMonster_Ice: '寒霜獸專用鞍具 (史詩)', //須找正確ID
      SkillUnlock_VolcanicMonster: '熔岩獸專用鞍具 (史詩)', //須找正確ID
      SkillUnlock_FireKirin_Dark: '邪麒麟專用鞍具 (史詩)', //須找正確ID
      SkillUnlock_FireKirin: '火麒麟專用鞍具 (史詩)', //須找正確ID
      SkillUnlock_GrassMammoth_Ice: '雪猛瑪專用鞍具 (史詩)', //須找正確ID
      SkillUnlock_GrassMammoth: '森猛獁專用鞍具 (史詩)', //須找正確ID
      SkillUnlock_BlueDragon: '碧海龍專用鞍具 (史詩)',
      SkillUnlock_Umihebi_Fire: '騰炎龍專用鞍具 (史詩)', //須找正確ID
      SkillUnlock_Umihebi: '覆海龍專用鞍具 (史詩)', //須找正確ID
      SkillUnlock_AmaterasuWolf: '蒼焰狼專用鞍具 (史詩)',
      SkillUnlock_ThunderDog: '霹靂犬專用鞍具 (史詩)',
      SkillUnlock_Manticore_Dark: '獄閻王專用鞍具 (史詩)', //須找正確ID
      SkillUnlock_Manticore: '獄焰王專用鞍具 (史詩)', //須找正確ID
      SkillUnlock_IceDeer: '嚴冬鹿專用鞍具 (史詩)',
      SkillUnlock_ThunderBird: '迅雷鳥專用鞍具 (史詩)',
      SkillUnlock_RedArmorBird: '燧火鳥專用鞍具 (史詩)',
      SkillUnlock_Horus: '荷魯斯專用鞍具 (史詩)',
      SkillUnlock_SkyDragon: '天羽龍專用鞍具 (史詩)',
      SkillUnlock_HadesBird: '雷冥鳥專用鞍具 (史詩)',
      SkillUnlock_FengyunDeeper: '雲海鹿專用鞍具 (史詩)',
      SkillUnlock_Suzaku_Water: '清雀專用鞍具 (史詩)', //須找正確ID
      SkillUnlock_Suzaku: '朱雀專用鞍具 (史詩)', //須找正確ID
      SkillUnlock_KingBahamut: '焰煌專用鞍具 (史詩)',
      SkillUnlock_Yeti_Grass: '綠苔絨怪專用鞍具 (史詩)',
      SkillUnlock_Yeti: '白絨雪怪專用鞍具 (史詩)',
      SkillUnlock_ElecPanda: '暴電熊專用機關槍 (傳奇)',
      SkillUnlock_BlackGriffon: '異構格里芬專用鞍具 (傳奇)',
      SkillUnlock_BlackMetalDragon: '魔淵龍專用鞍具 (傳奇)',
      SkillUnlock_LazyDragon_Electric: '派克龍專用飛彈發射器 (傳奇)', //須找正確ID
      SkillUnlock_LazyDragon: '佩克龍專用飛彈發射器 (傳奇)', //須找正確ID
      SkillUnlock_BlackFurDragon: '巨龍專用霰彈槍 (傳奇) ',
      SkillUnlock_IceHorse_Dark: '喚夜獸專用鞍具 (傳奇)',
      SkillUnlock_IceHorse: '喚冬獸專用鞍具 (傳奇)',
      SkillUnlock_SaintCentaur: '聖光騎士專用鞍具 (傳奇)',
      SkillUnlock_BlackCentaur: '混沌騎士專用鞍具 (傳奇)',
      SkillUnlock_JetDragon: '空渦龍專用飛彈發射器 (傳奇)',
      SkillUnlock_ElecLion: '利奧薩奇的鞍座 (傳奇)',
      SkillUnlock_GuardianDog: '守護犬的鞍座 (傳奇) ',
      SkillUnlock_DarkMutant: '達克內西斯的鞍座 (傳奇) ',
      SkillUnlock_GoldenHorse: '皇王的的鞍座 (傳奇) ',
      SkillUnlock_BadCatgirl: '不行的貓的霰彈槍 (傳奇)',
      SkillUnlock_FeatherOstrich: '蘇蔵的鞍座 (傳奇) ',
      SkillUnlock_WingGolem: '高人王的鞍座 (傳奇) ',
    },

    ...{
      //滑翔翼
      Glider_Old: '普通滑翔傘 (常見)',
      Glider_Good: '高級滑翔傘 (少見)',
      Glider_Super: '優級滑翔傘 (稀有)',
      Glider_Legendary: '特級滑翔傘 (史詩)',
      PV_Glider_Manta: 'PV預設的滑翔傘 (常見) ',
    },

    ...{
      //設計圖
      Blueprint_Head001_1: '王冠設計圖1 (常見)',
      Blueprint_Head002_1: '金色王冠設計圖1 (常見)',
      Blueprint_Head003_1: '長耳髮箍設計圖1 (常見)',
      Blueprint_Head004_1: '女巫帽設計圖1 (常見)',
      Blueprint_Head005_1: '費多拉帽設計圖1 (常見)',
      Blueprint_Head006_1: '安全帽設計圖1 (常見)',
      Blueprint_Head007_1: '大禮帽設計圖1 (常見)',
      Blueprint_Head008_1: '三角帽設計圖1 (常見)',
      Blueprint_Head009_1: '探險帽設計圖1 (常見)',
      Blueprint_Head010_1: '學士帽設計圖1 (常見)',
      Blueprint_Head011_1: '農夫帽設計圖1 (常見)',
      Blueprint_Head012_1: '博勒帽設計圖1 (常見)',
      Blueprint_Head013_1: '炸蛋鳥帽設計圖1 (常見)',
      Blueprint_Head014_1: '笑臉炸蛋鳥帽設計圖1 (常見)',
      Blueprint_Head015_1: '葉泥泥帽設計圖1 (常見)',
      Blueprint_Head016_1: '企丸王帽設計圖1 (常見)',
      Blueprint_Head017_1: '闇巫貓帽設計圖1 (常見)',
      Blueprint_WeakerBow_2: '老舊的弓設計圖1 (少見)',
      Blueprint_WeakerBow_3: '老舊的弓設計圖2 (稀有)',
      Blueprint_WeakerBow_4: '老舊的弓設計圖3 (史詩)',
      Blueprint_WeakerBow_5: '老舊的弓設計圖4 (傳奇)',
      Blueprint_BowGun_2: '十字弓設計圖1 (少見)',
      Blueprint_BowGun_3: '十字弓設計圖2 (稀有)',
      Blueprint_BowGun_4: '十字弓設計圖3 (史詩)',
      Blueprint_BowGun_5: '十字弓設計圖4 (傳奇)',
      Blueprint_AssaultRifle_Default2: '突擊步槍設計圖1 (少見)',
      Blueprint_AssaultRifle_Default3: '突擊步槍設計圖2 (稀有)',
      Blueprint_AssaultRifle_Default4: '突擊步槍設計圖3 (史詩)',
      Blueprint_AssaultRifle_Default5: '突擊步槍設計圖4 (傳奇)',
      Blueprint_PumpActionShotgun_2: '泵動式散彈槍設計圖1 (少見)',
      Blueprint_PumpActionShotgun_3: '泵動式散彈槍設計圖2 (稀有)',
      Blueprint_PumpActionShotgun_4: '泵動式散彈槍設計圖3 (史詩)',
      Blueprint_PumpActionShotgun_5: '泵動式散彈槍設計圖4 (傳奇)',
      Blueprint_HandGun_Default_2: '手槍設計圖1 (少見)',
      Blueprint_HandGun_Default_3: '手槍設計圖2 (稀有)',
      Blueprint_HandGun_Default_4: '手槍設計圖3 (史詩)',
      Blueprint_HandGun_Default_5: '手槍設計圖4 (傳奇)',
      Blueprint_Launcher_Default_2: '火箭彈發射器設計圖1 (少見)',
      Blueprint_Launcher_Default_3: '火箭彈發射器設計圖2 (稀有)',
      Blueprint_Launcher_Default_4: '火箭彈發射器設計圖3 (史詩)',
      Blueprint_Launcher_Default_5: '火箭彈發射器設計圖4 (傳奇)',
      Blueprint_FurHelmet_2: '羽毛髮飾設計圖1 (少見)',
      Blueprint_FurHelmet_3: '羽毛髮飾設計圖2 (稀有)',
      Blueprint_FurHelmet_4: '羽毛髮飾設計圖3 (史詩)',
      Blueprint_FurHelmet_5: '羽毛髮飾設計圖4 (傳奇)',
      Blueprint_CopperHelmet_2: '金屬頭盔設計圖1 (少見)',
      Blueprint_CopperHelmet_3: '金屬頭盔設計圖2 (稀有)',
      Blueprint_CopperHelmet_4: '金屬頭盔設計圖3 (史詩)',
      Blueprint_CopperHelmet_5: '金屬頭盔設計圖4 (傳奇)',
      Blueprint_IronHelmet_2: '精鍊金屬頭盔設計圖1 (少見)',
      Blueprint_IronHelmet_3: '精鍊金屬頭盔設計圖2 (稀有)',
      Blueprint_IronHelmet_4: '精鍊金屬頭盔設計圖3 (史詩)',
      Blueprint_IronHelmet_5: '精鍊金屬頭盔設計圖4 (傳奇)',
      Blueprint_StealHelmet_2: '帕魯金屬頭盔設計圖1 (少見)',
      Blueprint_StealHelmet_3: '帕魯金屬頭盔設計圖2 (稀有)',
      Blueprint_StealHelmet_4: '帕魯金屬頭盔設計圖3 (史詩)',
      Blueprint_StealHelmet_5: '帕魯金屬頭盔設計圖4 (傳奇)',
      Blueprint_ClothArmor_2: '布衣設計圖1 (少見)',
      Blueprint_ClothArmor_3: '布衣設計圖2 (稀有)',
      Blueprint_ClothArmor_4: '布衣設計圖3 (史詩)',
      Blueprint_ClothArmor_5: '布衣設計圖4 (傳奇)',
      Blueprint_FurArmor_2: '毛皮盔甲設計圖1 (少見)',
      Blueprint_FurArmor_3: '毛皮盔甲設計圖2 (稀有)',
      Blueprint_FurArmor_4: '毛皮盔甲設計圖3 (史詩)',
      Blueprint_FurArmor_5: '毛皮盔甲設計圖4 (傳奇)',
      Blueprint_CopperArmor_2: '金屬盔甲設計圖1 (少見)',
      Blueprint_CopperArmor_3: '金屬盔甲設計圖2 (稀有)',
      Blueprint_CopperArmor_4: '金屬盔甲設計圖3 (史詩)',
      Blueprint_CopperArmor_5: '金屬盔甲設計圖4 (傳奇)',
      Blueprint_IronArmor_2: '精鍊金屬盔甲設計圖1 (少見)',
      Blueprint_IronArmor_3: '精鍊金屬盔甲設計圖2 (稀有)',
      Blueprint_IronArmor_4: '精鍊金屬盔甲設計圖3 ()',
      Blueprint_IronArmor_5: '精鍊金屬盔甲設計圖4 (傳奇)',
      Blueprint_StealArmor_2: '帕魯金屬盔甲設計圖1 (少見)',
      Blueprint_StealArmor_3: '帕魯金屬盔甲設計圖2 (稀有)',
      Blueprint_StealArmor_4: '帕魯金屬盔甲設計圖3 (史詩)',
      Blueprint_StealArmor_5: '帕魯金屬盔甲設計圖4 (傳奇)',
      Blueprint_ClothArmorHeat_2: '熱帶地區民族服裝設計圖1 (少見)',
      Blueprint_ClothArmorHeat_3: '熱帶地區民族服裝設計圖2 (稀有)',
      Blueprint_ClothArmorHeat_4: '熱帶地區民族服裝設計圖3 (史詩)',
      Blueprint_ClothArmorHeat_5: '熱帶地區民族服裝設計圖4 (傳奇)',
      Blueprint_ClothArmorCold_2: '寒冷地區民族服裝設計圖1 (少見)',
      Blueprint_ClothArmorCold_3: '寒冷地區民族服裝設計圖2 (稀有)',
      Blueprint_ClothArmorCold_4: '寒冷地區民族服裝設計圖3 (史詩)',
      Blueprint_ClothArmorCold_5: '寒冷地區民族服裝設計圖4 (傳奇)',
      Blueprint_FurArmorHeat_2: '耐熱毛皮盔甲設計圖1 (少見)',
      Blueprint_FurArmorHeat_3: '耐熱毛皮盔甲設計圖2 (稀有)',
      Blueprint_FurArmorHeat_4: '耐熱毛皮盔甲設計圖3 (史詩)',
      Blueprint_FurArmorHeat_5: '耐熱毛皮盔甲設計圖4 (傳奇)',
      Blueprint_FurArmorCold_2: '耐寒毛皮盔甲設計圖1 (少見)',
      Blueprint_FurArmorCold_3: '耐寒毛皮盔甲設計圖2 (稀有)',
      Blueprint_FurArmorCold_4: '耐寒毛皮盔甲設計圖3 (史詩)',
      Blueprint_FurArmorCold_5: '耐寒毛皮盔甲設計圖4 (傳奇)',
      Blueprint_CopperArmorHeat_2: '耐熱金屬盔甲設計圖1 (少見)',
      Blueprint_CopperArmorHeat_3: '耐熱金屬盔甲設計圖2 (稀有)',
      Blueprint_CopperArmorHeat_4: '耐熱金屬盔甲設計圖3 (史詩)',
      Blueprint_CopperArmorHeat_5: '耐熱金屬盔甲設計圖4 (傳奇)',
      Blueprint_CopperArmorCold_2: '耐寒金屬盔甲設計圖1 (少見)',
      Blueprint_CopperArmorCold_3: '耐寒金屬盔甲設計圖2 (稀有)',
      Blueprint_CopperArmorCold_4: '耐寒金屬盔甲設計圖3 (史詩)',
      Blueprint_CopperArmorCold_5: '耐寒金屬盔甲設計圖4 (傳奇)',
      Blueprint_IronArmorHeat_2: '耐熱精鍊金屬盔甲設計圖1 (少見)',
      Blueprint_IronArmorHeat_3: '耐熱精鍊金屬盔甲設計圖2 (稀有)',
      Blueprint_IronArmorHeat_4: '耐熱精鍊金屬盔甲設計圖3 (史詩)',
      Blueprint_IronArmorHeat_5: '耐熱精鍊金屬盔甲設計圖4 (傳奇)',
      Blueprint_IronArmorCold_2: '耐寒精鍊金屬盔甲設計圖1 (少見)',
      Blueprint_IronArmorCold_3: '耐寒精鍊金屬盔甲設計圖2 (稀有)',
      Blueprint_IronArmorCold_4: '耐寒精鍊金屬盔甲設計圖3 (史詩)',
      Blueprint_IronArmorCold_5: '耐寒精鍊金屬盔甲設計圖4 (傳奇)',
      Blueprint_StealArmorHeat_2: '耐熱帕魯金屬盔甲設計圖1 (少見)',
      Blueprint_StealArmorHeat_3: '耐熱帕魯金屬盔甲設計圖2 (稀有)',
      Blueprint_StealArmorHeat_4: '耐熱帕魯金屬盔甲設計圖3 (史詩)',
      Blueprint_StealArmorHeat_5: '耐熱帕魯金屬盔甲設計圖4 (傳奇)',
      Blueprint_StealArmorCold_2: '耐寒帕魯金屬盔甲設計圖1 (少見)',
      Blueprint_StealArmorCold_3: '耐寒帕魯金屬盔甲設計圖2 (稀有)',
      Blueprint_StealArmorCold_4: '耐寒帕魯金屬盔甲設計圖3 (史詩)',
      Blueprint_StealArmorCold_5: '耐寒帕魯金屬盔甲設計圖4 (傳奇)',
      Blueprint_Head001_2: '王冠設計圖2 (少見)',
      Blueprint_Head001_3: '王冠設計圖3 (稀有)',
      Blueprint_Head001_4: '王冠設計圖4 (史詩)',
      Blueprint_Head001_5: '王冠設計圖5 (傳奇)',
      Blueprint_Head002_2: '金色王冠設計圖2 (少見)',
      Blueprint_Head002_3: '金色王冠設計圖3 (稀有)',
      Blueprint_Head002_4: '金色王冠設計圖4 (史詩)',
      Blueprint_Head002_5: '金色王冠設計圖5 (傳奇)',
      Blueprint_Head003_2: '長耳髮箍設計圖2 (少見)',
      Blueprint_Head003_3: '長耳髮箍設計圖3 (稀有)',
      Blueprint_Head003_4: '長耳髮箍設計圖4 (史詩)',
      Blueprint_Head003_5: '長耳髮箍設計圖5 (傳奇)',
      Blueprint_Head004_2: '女巫帽設計圖2 (少見)',
      Blueprint_Head004_3: '女巫帽設計圖3 (稀有)',
      Blueprint_Head004_4: '女巫帽設計圖4 (史詩)',
      Blueprint_Head004_5: '女巫帽設計圖5 (傳奇)',
      Blueprint_Head005_2: '費多拉帽設計圖2 (少見)',
      Blueprint_Head005_3: '費多拉帽設計圖3 (稀有)',
      Blueprint_Head005_4: '費多拉帽設計圖4 (史詩)',
      Blueprint_Head005_5: '費多拉帽設計圖5 (傳奇)',
      Blueprint_Head006_2: '安全帽設計圖2 (少見)',
      Blueprint_Head006_3: '安全帽設計圖3 (稀有)',
      Blueprint_Head006_4: '安全帽設計圖4 (史詩)',
      Blueprint_Head006_5: '安全帽設計圖5 (傳奇)',
      Blueprint_Head007_2: '大禮帽設計圖2 (少見)',
      Blueprint_Head007_3: '大禮帽設計圖3 (稀有)',
      Blueprint_Head007_4: '大禮帽設計圖4 (史詩)',
      Blueprint_Head007_5: '大禮帽設計圖5 (傳奇)',
      Blueprint_Head008_2: '三角帽設計圖2 (少見)',
      Blueprint_Head008_3: '三角帽設計圖3 (稀有)',
      Blueprint_Head008_4: '三角帽設計圖4 (史詩)',
      Blueprint_Head008_5: '三角帽設計圖5 (傳奇)',
      Blueprint_Head009_2: '探險帽設計圖2 (少見)',
      Blueprint_Head009_3: '探險帽設計圖3 (稀有)',
      Blueprint_Head009_4: '探險帽設計圖4 (史詩)',
      Blueprint_Head009_5: '探險帽設計圖5 (傳奇)',
      Blueprint_Head010_2: '學士帽設計圖2 (少見)',
      Blueprint_Head010_3: '學士帽設計圖3 (稀有)',
      Blueprint_Head010_4: '學士帽設計圖4 (史詩)',
      Blueprint_Head010_5: '學士帽設計圖5 (傳奇)',
      Blueprint_Head011_2: '農夫帽設計圖2 (少見)',
      Blueprint_Head011_3: '農夫帽設計圖3 (稀有)',
      Blueprint_Head011_4: '農夫帽設計圖4 (史詩)',
      Blueprint_Head011_5: '農夫帽設計圖5 (傳奇)',
      Blueprint_Head012_2: '博勒帽設計圖2 (少見)',
      Blueprint_Head012_3: '博勒帽設計圖3 (稀有)',
      Blueprint_Head012_4: '博勒帽設計圖4 (史詩)',
      Blueprint_Head012_5: '博勒帽設計圖5 (傳奇)',
      Blueprint_Head013_2: '炸蛋鳥帽設計圖2 (少見)',
      Blueprint_Head013_3: '炸蛋鳥帽設計圖3 (稀有)',
      Blueprint_Head013_4: '炸蛋鳥帽設計圖4 (史詩)',
      Blueprint_Head013_5: '炸蛋鳥帽設計圖5 (傳奇)',
      Blueprint_Head014_2: '笑臉炸蛋鳥帽設計圖2 (少見)',
      Blueprint_Head014_3: '笑臉炸蛋鳥帽設計圖3 (稀有)',
      Blueprint_Head014_4: '笑臉炸蛋鳥帽設計圖4 (史詩)',
      Blueprint_Head014_5: '笑臉炸蛋鳥帽設計圖5 (傳奇)',
      Blueprint_Head015_2: '葉泥泥帽設計圖2 (少見)',
      Blueprint_Head015_3: '葉泥泥帽設計圖3 (稀有)',
      Blueprint_Head015_4: '葉泥泥帽設計圖4 (史詩)',
      Blueprint_Head015_5: '葉泥泥帽設計圖5 (傳奇)',
      Blueprint_Head016_2: '企丸王帽設計圖2 (少見)',
      Blueprint_Head016_3: '企丸王帽設計圖3 (稀有)',
      Blueprint_Head016_4: '企丸王帽設計圖4 (史詩)',
      Blueprint_Head016_5: '企丸王帽設計圖5 (傳奇)',
      Blueprint_Head017_2: '闇巫貓帽設計圖2 (少見)',
      Blueprint_Head017_3: '闇巫貓帽設計圖3 (稀有)',
      Blueprint_Head017_4: '闇巫貓帽設計圖4 (史詩)',
      Blueprint_Head017_5: '闇巫貓帽設計圖5 (傳奇)',
      Blueprint_Musket_2: '鳥槍設計圖1 (少見)',
      Blueprint_Musket_3: '鳥槍設計圖2 (稀有)',
      Blueprint_Musket_4: '鳥槍設計圖3 (史詩)',
      Blueprint_Musket_5: '鳥槍設計圖4 (傳奇)',
      Blueprint_DoubleBarrelShotgun_2: '雙管散彈槍設計圖1 (少見)',
      Blueprint_DoubleBarrelShotgun_3: '雙管散彈槍設計圖2 (稀有)',
      Blueprint_DoubleBarrelShotgun_4: '雙管散彈槍設計圖3 (史詩)',
      Blueprint_DoubleBarrelShotgun_5: '雙管散彈槍設計圖4 (傳奇)',
      Blueprint_SingleShotRifle_2: '單發步槍設計圖1 (少見)',
      Blueprint_SingleShotRifle_3: '單發步槍設計圖2 (稀有)',
      Blueprint_SingleShotRifle_4: '單發步槍設計圖3 (史詩)',
      Blueprint_SingleShotRifle_5: '單發步槍設計圖4 (傳奇)',
    },
  };

  const html = await fs.readFile(path.join(__dirname, 'itemsweb.html'), {
    encoding: 'utf-8',
  });
  const $ = cheerio.load(html);

  // eslint-disable-next-line array-callback-return
  $('.col').map((_, col) => {
    const id = $(col).find('.flex-grow-1>div').text(); // code
    const name = $(col).find('a').text();
    const image = $(col).find('img').attr('src');
   // items[id] = { id, name, image };

    items[id] = name;
  });

  fs.writeFile(path.join(__dirname, 'items.js'), JSON.stringify(items), {
    encoding: 'utf-8',
  });
}

main();
